CREATE TABLE `wt_polls` (
  `cod` int(10) unsigned NOT NULL auto_increment,
  `dtstart` date NOT NULL default '0000-00-00',
  `dtend` date NOT NULL default '0000-00-00',
  `question` text NOT NULL,
  `item01` varchar(40) NOT NULL default '',
  `item02` varchar(40) NOT NULL default '',
  `item03` varchar(40) default NULL,
  `item04` varchar(40) default NULL,
  `item05` varchar(40) default NULL,
  `item06` varchar(40) default NULL,
  `item07` varchar(40) default NULL,
  `item08` varchar(40) default NULL,
  `item09` varchar(40) default NULL,
  `item10` varchar(40) default NULL,
  `count01` int(10) unsigned NOT NULL default '0',
  `count02` int(10) unsigned NOT NULL default '0',
  `count03` int(10) unsigned default '0',
  `count04` int(10) unsigned default '0',
  `count05` int(10) unsigned default '0',
  `count06` int(10) unsigned default '0',
  `count07` int(10) unsigned default NULL,
  `count08` int(10) unsigned default NULL,
  `count09` int(10) unsigned default NULL,
  `count10` int(10) unsigned default NULL,
  PRIMARY KEY  (`cod`),
  UNIQUE KEY `dtstInd` (`dtstart`)
) TYPE=MyISAM;

